#!/usr/bin/env python3
"""Assembles the /workspace/pkfit payload for Grok Bot.

Grok Bot has no SKILL.md upload path. Its Bots share a persistent Linux VM with a
filesystem, so the context pack ships as plain files the Bots read at the start of
every task. This script assembles that tree from the canonical documents so nothing
is duplicated in the repo.

Output: grok/workspace/dist/pkfit/  -> copy to /workspace/pkfit/ on the agent computer.
"""
import pathlib
import shutil

GROK = pathlib.Path(__file__).parent.parent
DIST = GROK / "workspace" / "dist" / "pkfit"

# canonical source -> name on the agent computer
FILES = {
    "skills/pkfit-stack/SKILL.md":  "CONTEXT.md",
    "skills/pkfit-voice/SKILL.md":  "VOICE.md",
    "skills/pkfit-design/SKILL.md": "DESIGN.md",
    "02_FUNNEL_MAP.md":             "FUNNEL.md",
    "01_MEDIA_PLAN.md":             "MEDIA.md",
    "phrase-bank.md":               "phrase-bank.md",
}

HEADER = (
    "<!-- Assembled by grok/workspace/build.py from {src} in PKFIT-architect-.\n"
    "     Do not edit this file on the agent computer. Edit the repo, rebuild, re-copy.\n"
    "     Edits made here are overwritten on the next sync and are lost. -->\n\n"
)

README = """# /workspace/pkfit

The PKFIT context pack. Every PKFIT Bot reads from here at the start of every task.

| File | What it is |
|------|------------|
| `CONTEXT.md` | The stack — operator, offer ladder with live URLs, properties, awareness stages |
| `VOICE.md` | The voice contract and the ethical floor. Binding on every word |
| `DESIGN.md` | Tokens, type, motion, image prompt preamble and negative prompt, video spec |
| `FUNNEL.md` | Awareness map, objection map, the email sequence |
| `MEDIA.md` | Channel thesis, cadence, metrics |
| `phrase-bank.md` | Verbatim audience language. The Listener appends here |
| `bots/` | The full brief for each Bot. Its charter points here |
| `out/` | Where Bots write deliverables |

## Rules

**Do not edit these files here.** They are generated from the `PKFIT-architect-` repo.
Edit there, rebuild, re-copy. Anything changed on this machine is lost on the next sync.

**This computer is shared by every Bot on the account. It is not a security boundary.**
Bots read each other's files and share browser sessions. Never place a credential, an API
key, a token, or a client's personal data anywhere under `/workspace`.

**No Bot publishes.** Deliverables land in `out/` and in the conversation. A human reviews
and posts.
"""

OUT_README = """# out/

Bot deliverables land here. Nothing in this directory is authoritative and nothing here
is backed up — treat it as a drop box the human empties.

Suggested convention: `out/<YYYY-MM-DD>/<bot-name>/`.

Never write a credential, an API key, or a client's personal data here. Every Bot on the
account can read this directory.
"""


def main():
    if DIST.exists():
        shutil.rmtree(DIST)
    (DIST / "bots").mkdir(parents=True)
    (DIST / "out").mkdir()

    for src, dest in FILES.items():
        text = (GROK / src).read_text()
        (DIST / dest).write_text(HEADER.format(src=f"grok/{src}") + text)
        print(f"  {dest:<16} <- grok/{src}")

    for bot in sorted((GROK / "bots").glob("*.md")):
        if bot.name == "README.md":
            continue
        text = (GROK / "bots" / bot.name).read_text()
        (DIST / "bots" / bot.name).write_text(
            HEADER.format(src=f"grok/bots/{bot.name}") + text)
        print(f"  bots/{bot.name}")

    (DIST / "README.md").write_text(README)
    (DIST / "out" / "README.md").write_text(OUT_README)

    total = sum(f.stat().st_size for f in DIST.rglob("*") if f.is_file())
    count = sum(1 for f in DIST.rglob("*") if f.is_file())
    print(f"\nassembled {count} files, {total/1024:.0f} KB -> {DIST}")
    print("copy this tree to /workspace/pkfit/ on the agent computer")


if __name__ == "__main__":
    main()
